### ISSUE TITLE
Staging changes

### ISSUE THREAD

**Issue by Ukendio** [matter-ecs/matter#29]
Sibling to #28 

Our current method of preventing iterator invalidation is via extra bookkeeping of the archetypes storage, which is quite expensive having to mark storages dirty/pristine and checking whether we have seen the entity while iterating.

An orthogonal solution would be to implement a way to defer changes by a system to the end of frame. There needs to be a way to annotate contextual information that helps systems be aware of each other, in which we can then implement sync points between them so that we can apply buffered changes before a system that depends on them.

**Comment by Ukendio** [comment]
We could implement sync points between systems that define that they want to be *after* a certain system. However it is still TBD on how we resolve systems that implement a "low" priority. Side note, priority is kind of a weird...

**Comment by LastTalon** [comment]
I think pipelines/schedules are the way to go here. It lets users have a say in that process and makes it more transparent to them. Letting the user choose their sync point helps them understand better when they're crossing that boundary. And it also lets us do things that require them to be more forgiving since they can see the process better. For example, having updates not happen for concurrent systems within the same pipeline is more understandable as long as they sync when the pipeline is complete (this incidentally makes things easier if we ever do get parallelism, too).

**Comment by Ukendio** [comment]
Fixed in #30
